window.CARS = [
 {
  "id": "mercedes-benz-clase-e",
  "brand": "Mercedes-Benz",
  "model": "Clase E",
  "version": "E 300 de",
  "price": 34500,
  "financed": 34499,
  "monthly": 369,
  "year": 2021,
  "km": 97000,
  "fuel": "Híbrido enchufable",
  "gear": "Automático",
  "cv": 306,
  "doors": 4,
  "seats": 5,
  "body": "Berlina",
  "co2": "38",
  "label": "0",
  "cons": "0.4",
  "traction": "Tracción trasera",
  "vmax": "250",
  "accel": "5.9",
  "cc": "1950",
  "status": "Disponible",
  "isNew": true,
  "city": "València",
  "imgs": [
   "mercedes-benz-clase-e-1.jpg",
   "mercedes-benz-clase-e-2.jpg",
   "mercedes-benz-clase-e-3.jpg",
   "mercedes-benz-clase-e-4.jpg",
   "mercedes-benz-clase-e-5.jpg",
   "mercedes-benz-clase-e-6.jpg",
   "mercedes-benz-clase-e-7.jpg",
   "mercedes-benz-clase-e-8.jpg"
  ]
 },
 {
  "id": "hyundai-i30",
  "brand": "Hyundai",
  "model": "i30",
  "version": "1.0 TGDI N Line 30 Aniversario",
  "price": 18495,
  "financed": 18981,
  "monthly": 181,
  "year": 2023,
  "km": 33000,
  "fuel": "Gasolina",
  "gear": "Manual",
  "cv": 120,
  "doors": 5,
  "seats": 5,
  "body": "Familiar",
  "co2": null,
  "label": "C",
  "cons": "6.1",
  "traction": "Tracción delantera",
  "vmax": "196",
  "accel": "11.4",
  "cc": "998",
  "status": "Disponible",
  "isNew": true,
  "city": "València",
  "imgs": [
   "hyundai-i30-1.jpg",
   "hyundai-i30-2.jpg",
   "hyundai-i30-3.jpg",
   "hyundai-i30-4.jpg",
   "hyundai-i30-5.jpg",
   "hyundai-i30-6.jpg",
   "hyundai-i30-7.jpg",
   "hyundai-i30-8.jpg"
  ]
 },
 {
  "id": "toyota-corolla",
  "brand": "Toyota",
  "model": "Corolla",
  "version": "140H Active Plus Touring Sport",
  "price": 21891,
  "financed": 21881,
  "monthly": 216,
  "year": 2023,
  "km": 114700,
  "fuel": "Híbrido",
  "gear": "Automático",
  "cv": 140,
  "doors": 5,
  "seats": 5,
  "body": "Familiar",
  "co2": null,
  "label": "ECO",
  "cons": "4.5",
  "traction": "Tracción delantera",
  "vmax": "180",
  "accel": "9.2",
  "cc": "1798",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "toyota-corolla-1.jpg",
   "toyota-corolla-2.jpg",
   "toyota-corolla-3.jpg",
   "toyota-corolla-4.jpg",
   "toyota-corolla-5.jpg",
   "toyota-corolla-6.jpg",
   "toyota-corolla-7.jpg",
   "toyota-corolla-8.jpg"
  ]
 },
 {
  "id": "bmw-x7",
  "brand": "BMW",
  "model": "X7",
  "version": "M60i xDrive",
  "price": 141959,
  "financed": 141951,
  "monthly": 1673,
  "year": 2024,
  "km": 30000,
  "fuel": "Híbrido",
  "gear": "Automático",
  "cv": 530,
  "doors": 5,
  "seats": 7,
  "body": "Cuatro_por_cuatro_suv",
  "co2": null,
  "label": "ECO",
  "cons": "12.1",
  "traction": "4x4",
  "vmax": "250",
  "accel": "4.7",
  "cc": "4395",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "bmw-x7-1.jpg",
   "bmw-x7-2.jpg",
   "bmw-x7-3.jpg",
   "bmw-x7-4.jpg",
   "bmw-x7-5.jpg",
   "bmw-x7-6.jpg",
   "bmw-x7-7.jpg",
   "bmw-x7-8.jpg"
  ]
 },
 {
  "id": "porsche-boxster",
  "brand": "Porsche",
  "model": "Boxster",
  "version": "S 3.2 MY07",
  "price": 31945,
  "financed": 31941,
  "monthly": 338,
  "year": 2006,
  "km": 107000,
  "fuel": "Gasolina",
  "gear": "Manual",
  "cv": 280,
  "doors": 2,
  "seats": 2,
  "body": "Descapotable",
  "co2": "248",
  "label": null,
  "cons": "10.4",
  "traction": "Tracción trasera",
  "vmax": "268",
  "accel": "5.5",
  "cc": "3179",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "porsche-boxster-1.jpg",
   "porsche-boxster-2.jpg",
   "porsche-boxster-3.jpg",
   "porsche-boxster-4.jpg",
   "porsche-boxster-5.jpg",
   "porsche-boxster-6.jpg",
   "porsche-boxster-7.jpg",
   "porsche-boxster-8.jpg"
  ]
 },
 {
  "id": "bmw-x5",
  "brand": "BMW",
  "model": "X5",
  "version": "xDrive35i",
  "price": 23405,
  "financed": 23399,
  "monthly": 283,
  "year": 2017,
  "km": 135000,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 306,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "197",
  "label": null,
  "cons": "8.5",
  "traction": "4x4",
  "vmax": "235",
  "accel": "6.5",
  "cc": "2979",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "bmw-x5-1.jpg",
   "bmw-x5-2.jpg",
   "bmw-x5-3.jpg",
   "bmw-x5-4.jpg",
   "bmw-x5-5.jpg",
   "bmw-x5-6.jpg",
   "bmw-x5-7.jpg",
   "bmw-x5-8.jpg"
  ]
 },
 {
  "id": "cupra-formentor",
  "brand": "Cupra",
  "model": "Formentor",
  "version": "1.5 TSI 110kW (150 CV) DSG",
  "price": 24791,
  "financed": 24785,
  "monthly": 300,
  "year": 2024,
  "km": 59000,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 150,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "126",
  "label": "C",
  "cons": "5.5",
  "traction": "Tracción delantera",
  "vmax": "203",
  "accel": "8.9",
  "cc": "1498",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "cupra-formentor-1.jpg",
   "cupra-formentor-2.jpg",
   "cupra-formentor-3.jpg",
   "cupra-formentor-4.jpg",
   "cupra-formentor-5.jpg",
   "cupra-formentor-6.jpg",
   "cupra-formentor-7.jpg",
   "cupra-formentor-8.jpg"
  ]
 },
 {
  "id": "bmw-serie-2",
  "brand": "BMW",
  "model": "Serie 2",
  "version": "M240iA xDrive",
  "price": 34795,
  "financed": 34791,
  "monthly": 421,
  "year": 2020,
  "km": 65500,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 340,
  "doors": 2,
  "seats": 4,
  "body": "Coupé",
  "co2": "178",
  "label": "C",
  "cons": "7.8",
  "traction": "4x4",
  "vmax": "250",
  "accel": "4.4",
  "cc": "2998",
  "status": "En preparación",
  "isNew": false,
  "city": "València",
  "imgs": [
   "bmw-serie-2-1.jpg",
   "bmw-serie-2-2.jpg",
   "bmw-serie-2-3.jpg",
   "bmw-serie-2-4.jpg",
   "bmw-serie-2-5.jpg",
   "bmw-serie-2-6.jpg",
   "bmw-serie-2-7.jpg",
   "bmw-serie-2-8.jpg"
  ]
 },
 {
  "id": "toyota-corolla-2",
  "brand": "Toyota",
  "model": "Corolla",
  "version": "140H Active Plus Touring Sport",
  "price": 26891,
  "financed": 27500,
  "monthly": null,
  "year": 2024,
  "km": 16500,
  "fuel": "Híbrido",
  "gear": "Automático",
  "cv": 140,
  "doors": 5,
  "seats": 5,
  "body": "Familiar",
  "co2": null,
  "label": "ECO",
  "cons": "4.5",
  "traction": "Tracción delantera",
  "vmax": "180",
  "accel": "9.2",
  "cc": "1798",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "toyota-corolla-2-1.jpg",
   "toyota-corolla-2-2.jpg",
   "toyota-corolla-2-3.jpg",
   "toyota-corolla-2-4.jpg",
   "toyota-corolla-2-5.jpg",
   "toyota-corolla-2-6.jpg",
   "toyota-corolla-2-7.jpg",
   "toyota-corolla-2-8.jpg"
  ]
 },
 {
  "id": "peugeot-3008",
  "brand": "Peugeot",
  "model": "3008",
  "version": "1.6BLUEHDI 120 HP ALLURE S&S",
  "price": 16705,
  "financed": 16700,
  "monthly": 202,
  "year": 2016,
  "km": 31000,
  "fuel": "Diésel",
  "gear": "Automático",
  "cv": 120,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "104",
  "label": null,
  "cons": "4",
  "traction": "Tracción delantera",
  "vmax": "189",
  "accel": "11.2",
  "cc": "1560",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "peugeot-3008-1.jpg",
   "peugeot-3008-2.jpg",
   "peugeot-3008-3.jpg",
   "peugeot-3008-4.jpg",
   "peugeot-3008-5.jpg",
   "peugeot-3008-6.jpg",
   "peugeot-3008-7.jpg",
   "peugeot-3008-8.jpg"
  ]
 },
 {
  "id": "toyota-corolla-cross",
  "brand": "Toyota",
  "model": "Corolla Cross",
  "version": "Style Plus 2.0l",
  "price": 29871,
  "financed": 30999,
  "monthly": null,
  "year": 2023,
  "km": 85500,
  "fuel": "Híbrido",
  "gear": "Automático",
  "cv": 197,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": null,
  "label": "ECO",
  "cons": "5.1",
  "traction": "Tracción delantera",
  "vmax": "180",
  "accel": "7.7",
  "cc": "1987",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "toyota-corolla-cross-1.jpg",
   "toyota-corolla-cross-2.jpg",
   "toyota-corolla-cross-3.jpg",
   "toyota-corolla-cross-4.jpg",
   "toyota-corolla-cross-5.jpg",
   "toyota-corolla-cross-6.jpg",
   "toyota-corolla-cross-7.jpg",
   "toyota-corolla-cross-8.jpg"
  ]
 },
 {
  "id": "audi-a3",
  "brand": "Audi",
  "model": "A3",
  "version": "2.0 TDI 110kW (150CV) S tronic Sportback",
  "price": 15750,
  "financed": 14899,
  "monthly": null,
  "year": 2018,
  "km": 115500,
  "fuel": "Diésel",
  "gear": "Automático",
  "cv": 150,
  "doors": 5,
  "seats": 5,
  "body": "Compacto",
  "co2": "114",
  "label": null,
  "cons": "4.4",
  "traction": "Tracción delantera",
  "vmax": "218",
  "accel": "8.3",
  "cc": "1968",
  "status": "Reservado",
  "isNew": false,
  "city": "València",
  "imgs": [
   "audi-a3-1.jpg",
   "audi-a3-2.jpg",
   "audi-a3-3.jpg",
   "audi-a3-4.jpg",
   "audi-a3-5.jpg",
   "audi-a3-6.jpg",
   "audi-a3-7.jpg",
   "audi-a3-8.jpg"
  ]
 },
 {
  "id": "land-rover-range-rover-velar",
  "brand": "Land Rover",
  "model": "Range Rover Velar",
  "version": "2.0 D180 132kW R-Dynamic 4WD Auto",
  "price": 28895,
  "financed": 28999,
  "monthly": null,
  "year": 2019,
  "km": 139000,
  "fuel": "Diésel",
  "gear": "Automático",
  "cv": 180,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "152",
  "label": "C",
  "cons": "5.7",
  "traction": "4x4",
  "vmax": "201",
  "accel": "8.9",
  "cc": "1999",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "land-rover-range-rover-velar-1.jpg",
   "land-rover-range-rover-velar-2.jpg",
   "land-rover-range-rover-velar-3.jpg",
   "land-rover-range-rover-velar-4.jpg",
   "land-rover-range-rover-velar-5.jpg",
   "land-rover-range-rover-velar-6.jpg",
   "land-rover-range-rover-velar-7.jpg",
   "land-rover-range-rover-velar-8.jpg"
  ]
 },
 {
  "id": "toyota-corolla-3",
  "brand": "Toyota",
  "model": "Corolla",
  "version": "1.8 125H ACTIVE TECH E-CVT",
  "price": 15399,
  "financed": 15499,
  "monthly": null,
  "year": 2021,
  "km": 204000,
  "fuel": "Híbrido",
  "gear": "Automático",
  "cv": 122,
  "doors": 5,
  "seats": 5,
  "body": "Compacto",
  "co2": "76",
  "label": "ECO",
  "cons": "3.3",
  "traction": "Tracción delantera",
  "vmax": "180",
  "accel": "10.9",
  "cc": "1798",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "toyota-corolla-3-1.jpg",
   "toyota-corolla-3-2.jpg",
   "toyota-corolla-3-3.jpg",
   "toyota-corolla-3-4.jpg",
   "toyota-corolla-3-5.jpg",
   "toyota-corolla-3-6.jpg",
   "toyota-corolla-3-7.jpg",
   "toyota-corolla-3-8.jpg"
  ]
 },
 {
  "id": "toyota-corolla-4",
  "brand": "Toyota",
  "model": "Corolla",
  "version": "1.8 125H ACTIVE TECH E-CVT",
  "price": 15399,
  "financed": 15499,
  "monthly": null,
  "year": 2021,
  "km": 42500,
  "fuel": "Híbrido",
  "gear": "Automático",
  "cv": 122,
  "doors": 5,
  "seats": 5,
  "body": "Compacto",
  "co2": "76",
  "label": "ECO",
  "cons": "3.3",
  "traction": "Tracción delantera",
  "vmax": "180",
  "accel": "10.9",
  "cc": "1798",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "toyota-corolla-4-1.jpg",
   "toyota-corolla-4-2.jpg",
   "toyota-corolla-4-3.jpg",
   "toyota-corolla-4-4.jpg",
   "toyota-corolla-4-5.jpg",
   "toyota-corolla-4-6.jpg",
   "toyota-corolla-4-7.jpg",
   "toyota-corolla-4-8.jpg"
  ]
 },
 {
  "id": "skoda-octavia",
  "brand": "Škoda",
  "model": "Octavia",
  "version": "1.0 TSI 115cv DSG Ambition",
  "price": 11895,
  "financed": 12000,
  "monthly": null,
  "year": 2017,
  "km": 115500,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 115,
  "doors": 5,
  "seats": 5,
  "body": "Compacto",
  "co2": "106",
  "label": null,
  "cons": "4.5",
  "traction": "Tracción delantera",
  "vmax": "202",
  "accel": "10",
  "cc": "999",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "skoda-octavia-1.jpg",
   "skoda-octavia-2.jpg",
   "skoda-octavia-3.jpg",
   "skoda-octavia-4.jpg",
   "skoda-octavia-5.jpg",
   "skoda-octavia-6.jpg",
   "skoda-octavia-7.jpg",
   "skoda-octavia-8.jpg"
  ]
 },
 {
  "id": "renault-clio",
  "brand": "Renault",
  "model": "Clio",
  "version": "Limited TCe 66kW (90CV) -18",
  "price": 9391,
  "financed": 9500,
  "monthly": null,
  "year": 2018,
  "km": 102500,
  "fuel": "Gasolina",
  "gear": "Manual",
  "cv": 90,
  "doors": 5,
  "seats": 5,
  "body": "Compacto",
  "co2": "113",
  "label": "C",
  "cons": "5",
  "traction": "Tracción delantera",
  "vmax": "178",
  "accel": "12.1",
  "cc": "898",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "renault-clio-1.jpg",
   "renault-clio-2.jpg",
   "renault-clio-3.jpg",
   "renault-clio-4.jpg",
   "renault-clio-5.jpg",
   "renault-clio-6.jpg",
   "renault-clio-7.jpg",
   "renault-clio-8.jpg"
  ]
 },
 {
  "id": "skoda-kamiq",
  "brand": "Škoda",
  "model": "Kamiq",
  "version": "1.0 TSI 81kW (110CV) DSG Ambition",
  "price": 16895,
  "financed": 17000,
  "monthly": null,
  "year": 2022,
  "km": 85000,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 110,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "112",
  "label": "C",
  "cons": "5.9",
  "traction": "Tracción delantera",
  "vmax": "193",
  "accel": null,
  "cc": "999",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "skoda-kamiq-1.jpg",
   "skoda-kamiq-2.jpg",
   "skoda-kamiq-3.jpg",
   "skoda-kamiq-4.jpg",
   "skoda-kamiq-5.jpg",
   "skoda-kamiq-6.jpg"
  ]
 },
 {
  "id": "nissan-juke",
  "brand": "Nissan",
  "model": "JUKE",
  "version": "G EU6 69 kW (94 CV) 5M/T VISIA",
  "price": 11865,
  "financed": null,
  "monthly": null,
  "year": 2016,
  "km": 64300,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 94,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "138",
  "label": null,
  "cons": "6",
  "traction": "Tracción delantera",
  "vmax": "168",
  "accel": "12",
  "cc": "1598",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "nissan-juke-1.jpg",
   "nissan-juke-2.jpg",
   "nissan-juke-3.jpg",
   "nissan-juke-4.jpg",
   "nissan-juke-5.jpg",
   "nissan-juke-6.jpg",
   "nissan-juke-7.jpg",
   "nissan-juke-8.jpg"
  ]
 },
 {
  "id": "volkswagen-touareg",
  "brand": "Volkswagen",
  "model": "Touareg",
  "version": "Prem Eleg 3.0 V6 TDI 170kW Tip 4M",
  "price": 28851,
  "financed": null,
  "monthly": null,
  "year": 2022,
  "km": 220000,
  "fuel": "Diésel",
  "gear": "Automático",
  "cv": 231,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": null,
  "label": "C",
  "cons": "8",
  "traction": "4x4",
  "vmax": "218",
  "accel": "7.5",
  "cc": "2967",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "volkswagen-touareg-1.jpg",
   "volkswagen-touareg-2.jpg",
   "volkswagen-touareg-3.jpg",
   "volkswagen-touareg-4.jpg",
   "volkswagen-touareg-5.jpg",
   "volkswagen-touareg-6.jpg",
   "volkswagen-touareg-7.jpg",
   "volkswagen-touareg-8.jpg"
  ]
 },
 {
  "id": "mazda-cx-5",
  "brand": "Mazda",
  "model": "CX-5",
  "version": "2.2 150cv DE 2WD Style",
  "price": 12891,
  "financed": null,
  "monthly": null,
  "year": 2014,
  "km": 143000,
  "fuel": "Diésel",
  "gear": "Automático",
  "cv": 150,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "119",
  "label": null,
  "cons": "4.6",
  "traction": "Tracción delantera",
  "vmax": "202",
  "accel": "9.2",
  "cc": "2184",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "mazda-cx-5-1.jpg",
   "mazda-cx-5-2.jpg",
   "mazda-cx-5-3.jpg",
   "mazda-cx-5-4.jpg",
   "mazda-cx-5-5.jpg",
   "mazda-cx-5-6.jpg",
   "mazda-cx-5-7.jpg"
  ]
 },
 {
  "id": "mercedes-benz-eqa",
  "brand": "Mercedes-Benz",
  "model": "EQA",
  "version": "EQA 250",
  "price": 28391,
  "financed": 22999,
  "monthly": null,
  "year": 2022,
  "km": 46500,
  "fuel": "Eléctrico",
  "gear": "Automático",
  "cv": 190,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "0",
  "label": "0",
  "cons": null,
  "traction": "Tracción delantera",
  "vmax": "160",
  "accel": "8.9",
  "cc": null,
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "mercedes-benz-eqa-1.jpg",
   "mercedes-benz-eqa-2.jpg",
   "mercedes-benz-eqa-3.jpg",
   "mercedes-benz-eqa-4.jpg",
   "mercedes-benz-eqa-5.jpg",
   "mercedes-benz-eqa-6.jpg",
   "mercedes-benz-eqa-7.jpg",
   "mercedes-benz-eqa-8.jpg"
  ]
 },
 {
  "id": "toyota-rav4",
  "brand": "Toyota",
  "model": "Rav4",
  "version": "2.5l PLUG-IN 300PH (e-CVT) Style Plus",
  "price": 36725,
  "financed": null,
  "monthly": null,
  "year": 2023,
  "km": 88400,
  "fuel": "Híbrido enchufable",
  "gear": "Automático",
  "cv": 306,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "26",
  "label": "0",
  "cons": "1.2",
  "traction": "4x4",
  "vmax": "180",
  "accel": "6",
  "cc": "2487",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "toyota-rav4-1.jpg",
   "toyota-rav4-2.jpg",
   "toyota-rav4-3.jpg",
   "toyota-rav4-4.jpg",
   "toyota-rav4-5.jpg",
   "toyota-rav4-6.jpg",
   "toyota-rav4-7.jpg"
  ]
 },
 {
  "id": "peugeot-2008",
  "brand": "Peugeot",
  "model": "2008",
  "version": "Allure 1.2 PureTech 81KW 110CVSS EAT6",
  "price": 9845,
  "financed": null,
  "monthly": null,
  "year": 2017,
  "km": 89200,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 110,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "110",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1199",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "peugeot-2008-1.jpg",
   "peugeot-2008-2.jpg",
   "peugeot-2008-3.jpg",
   "peugeot-2008-4.jpg",
   "peugeot-2008-5.jpg",
   "peugeot-2008-6.jpg",
   "peugeot-2008-7.jpg",
   "peugeot-2008-8.jpg"
  ]
 },
 {
  "id": "kia-ceed-tourer",
  "brand": "Kia",
  "model": "Ceed Tourer",
  "version": "Tourer 1.6 MHEV iMT 100kW Tech",
  "price": 13865,
  "financed": null,
  "monthly": null,
  "year": 2021,
  "km": 173500,
  "fuel": "Híbrido",
  "gear": "Automático",
  "cv": 136,
  "doors": 5,
  "seats": 5,
  "body": "Berlina",
  "co2": "0",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1598",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "kia-ceed-tourer-1.jpg",
   "kia-ceed-tourer-2.jpg",
   "kia-ceed-tourer-3.jpg",
   "kia-ceed-tourer-4.jpg",
   "kia-ceed-tourer-5.jpg",
   "kia-ceed-tourer-6.jpg",
   "kia-ceed-tourer-7.jpg",
   "kia-ceed-tourer-8.jpg"
  ]
 },
 {
  "id": "peugeot-408",
  "brand": "Peugeot",
  "model": "408",
  "version": "408 GT PLUGIN HYBRID 225 eEAT8",
  "price": 30891,
  "financed": null,
  "monthly": null,
  "year": 2024,
  "km": 44180,
  "fuel": "Híbrido enchufable",
  "gear": "Automático",
  "cv": 225,
  "doors": 5,
  "seats": 5,
  "body": "Berlina",
  "co2": "0",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1598",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "peugeot-408-1.jpg",
   "peugeot-408-2.jpg",
   "peugeot-408-3.jpg",
   "peugeot-408-4.jpg",
   "peugeot-408-5.jpg",
   "peugeot-408-6.jpg",
   "peugeot-408-7.jpg",
   "peugeot-408-8.jpg"
  ]
 },
 {
  "id": "audi-a7",
  "brand": "Audi",
  "model": "A7",
  "version": "Sportback 55 TFSI 250kW quattro S tronic",
  "price": 41841,
  "financed": null,
  "monthly": null,
  "year": 2020,
  "km": 114000,
  "fuel": "Híbrido",
  "gear": "Automático",
  "cv": 340,
  "doors": 5,
  "seats": 4,
  "body": "Berlina",
  "co2": "163",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "2995",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "audi-a7-1.jpg",
   "audi-a7-2.jpg",
   "audi-a7-3.jpg",
   "audi-a7-4.jpg",
   "audi-a7-5.jpg",
   "audi-a7-6.jpg",
   "audi-a7-7.jpg",
   "audi-a7-8.jpg"
  ]
 },
 {
  "id": "ford-fiesta",
  "brand": "Ford",
  "model": "Fiesta",
  "version": "1.1 TiVCT 63kW Trend 5p",
  "price": 9291,
  "financed": null,
  "monthly": null,
  "year": 2018,
  "km": 90900,
  "fuel": "Gasolina",
  "gear": "Manual",
  "cv": 85,
  "doors": 5,
  "seats": 5,
  "body": "Berlina",
  "co2": "117",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1084",
  "status": "En preparación",
  "isNew": false,
  "city": "València",
  "imgs": [
   "ford-fiesta-1.jpg",
   "ford-fiesta-2.jpg",
   "ford-fiesta-3.jpg",
   "ford-fiesta-4.jpg",
   "ford-fiesta-5.jpg",
   "ford-fiesta-6.jpg",
   "ford-fiesta-7.jpg",
   "ford-fiesta-8.jpg"
  ]
 },
 {
  "id": "audi-tts",
  "brand": "Audi",
  "model": "TTS",
  "version": "Coupe 2.0 TFSI 310CV quattro",
  "price": 32851,
  "financed": null,
  "monthly": null,
  "year": 2016,
  "km": 85000,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 310,
  "doors": 3,
  "seats": 4,
  "body": "Coupé",
  "co2": "164",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1984",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "audi-tts-1.jpg",
   "audi-tts-2.jpg",
   "audi-tts-3.jpg",
   "audi-tts-4.jpg",
   "audi-tts-5.jpg",
   "audi-tts-6.jpg",
   "audi-tts-7.jpg",
   "audi-tts-8.jpg"
  ]
 },
 {
  "id": "audi-q3",
  "brand": "Audi",
  "model": "Q3",
  "version": "2.0 TFSI 170cv quattro S tronic Ambition",
  "price": 13399,
  "financed": null,
  "monthly": null,
  "year": 2013,
  "km": 178000,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 170,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "179",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1984",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "audi-q3-1.jpg",
   "audi-q3-2.jpg",
   "audi-q3-3.jpg",
   "audi-q3-4.jpg",
   "audi-q3-5.jpg",
   "audi-q3-6.jpg",
   "audi-q3-7.jpg",
   "audi-q3-8.jpg"
  ]
 },
 {
  "id": "mini-mini",
  "brand": "MINI",
  "model": "MINI",
  "version": "Cooper Coupe",
  "price": 7861,
  "financed": null,
  "monthly": null,
  "year": 2011,
  "km": 160000,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 122,
  "doors": 2,
  "seats": 2,
  "body": "Coupé",
  "co2": "127",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1598",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "mini-mini-1.jpg",
   "mini-mini-2.jpg",
   "mini-mini-3.jpg",
   "mini-mini-4.jpg",
   "mini-mini-5.jpg",
   "mini-mini-6.jpg",
   "mini-mini-7.jpg",
   "mini-mini-8.jpg"
  ]
 },
 {
  "id": "bmw-x3",
  "brand": "BMW",
  "model": "X3",
  "version": "xDrive28i",
  "price": 18615,
  "financed": null,
  "monthly": null,
  "year": 2016,
  "km": 146000,
  "fuel": "Gasolina",
  "gear": "Automático",
  "cv": 245,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "169",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1997",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "bmw-x3-1.jpg",
   "bmw-x3-2.jpg",
   "bmw-x3-3.jpg",
   "bmw-x3-4.jpg",
   "bmw-x3-5.jpg",
   "bmw-x3-6.jpg",
   "bmw-x3-7.jpg",
   "bmw-x3-8.jpg"
  ]
 },
 {
  "id": "kia-sportage",
  "brand": "Kia",
  "model": "Sportage",
  "version": "1.7 CRDi VGT 85kW Drive 4x2 EcoDynamics",
  "price": 14401,
  "financed": null,
  "monthly": null,
  "year": 2017,
  "km": 136000,
  "fuel": "Diésel",
  "gear": "Automático",
  "cv": 115,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "119",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1685",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "kia-sportage-1.jpg",
   "kia-sportage-2.jpg",
   "kia-sportage-3.jpg",
   "kia-sportage-4.jpg",
   "kia-sportage-5.jpg",
   "kia-sportage-6.jpg",
   "kia-sportage-7.jpg",
   "kia-sportage-8.jpg"
  ]
 },
 {
  "id": "opel-crossland-x",
  "brand": "Opel",
  "model": "Crossland X",
  "version": "1.2T 81kW 110CV ecoTEC Excellence SS",
  "price": 9370,
  "financed": null,
  "monthly": null,
  "year": 2017,
  "km": 64000,
  "fuel": "Gasolina",
  "gear": "Manual",
  "cv": 110,
  "doors": 5,
  "seats": 5,
  "body": "Cuatro_por_cuatro_suv",
  "co2": "111",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1199",
  "status": "En preparación",
  "isNew": false,
  "city": "València",
  "imgs": [
   "opel-crossland-x-1.jpg",
   "opel-crossland-x-2.jpg",
   "opel-crossland-x-3.jpg",
   "opel-crossland-x-4.jpg",
   "opel-crossland-x-5.jpg",
   "opel-crossland-x-6.jpg",
   "opel-crossland-x-7.jpg",
   "opel-crossland-x-8.jpg"
  ]
 },
 {
  "id": "citroen-grand-c4-picasso",
  "brand": "Citroën",
  "model": "Grand C4 Picasso",
  "version": "BlueHDi 120cv Feel Edition",
  "price": 9851,
  "financed": null,
  "monthly": null,
  "year": 2016,
  "km": 127000,
  "fuel": "Diésel",
  "gear": "Manual",
  "cv": 120,
  "doors": 5,
  "seats": 7,
  "body": "Monovolumen",
  "co2": "106",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1560",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "citroen-grand-c4-picasso-1.jpg",
   "citroen-grand-c4-picasso-2.jpg",
   "citroen-grand-c4-picasso-3.jpg",
   "citroen-grand-c4-picasso-4.jpg",
   "citroen-grand-c4-picasso-5.jpg",
   "citroen-grand-c4-picasso-6.jpg",
   "citroen-grand-c4-picasso-7.jpg",
   "citroen-grand-c4-picasso-8.jpg"
  ]
 },
 {
  "id": "mini-countryman",
  "brand": "MINI",
  "model": "Countryman",
  "version": "Cooper SE ALL4",
  "price": 27581,
  "financed": null,
  "monthly": null,
  "year": 2022,
  "km": 31000,
  "fuel": "Eléctrico",
  "gear": "Automático",
  "cv": 220,
  "doors": 5,
  "seats": 5,
  "body": "Berlina",
  "co2": "0",
  "label": null,
  "cons": null,
  "traction": null,
  "vmax": null,
  "accel": null,
  "cc": "1499",
  "status": "Disponible",
  "isNew": false,
  "city": "València",
  "imgs": [
   "mini-countryman-1.jpg",
   "mini-countryman-2.jpg",
   "mini-countryman-3.jpg",
   "mini-countryman-4.jpg",
   "mini-countryman-5.jpg",
   "mini-countryman-6.jpg",
   "mini-countryman-7.jpg",
   "mini-countryman-8.jpg"
  ]
 }
];
